### ISSUE TITLE
Cannot install a package which has a dependency on the OS architecture

### ISSUE THREAD

**Issue by morozov** [phpbrew/PEARX#8]
<details>
  <summary>phpbrew ext install sqlsrv</summary>

```
Warning: Some extension won't be able to be built with php7. If the extension
supports php7 in another branch or new major version, you will need to specify
the branch name or version name explicitly.

For example, to install memcached extension for php7, use:

    phpbrew ext install github:php-memcached-dev/php-memcached php7 -- --disable-memcached-sasl

PHP Fatal error:  Uncaught Exception: invalid pear dependency type. in /home/morozov/Projects/phpbrew/vendor/corneltek/pearx/src/PEARX/Package.php:278
Stack trace:
#0 /home/morozov/Projects/phpbrew/vendor/corneltek/pearx/src/PEARX/Package.php(310): PEARX\Package->validateDependencyType('arch')
#1 /home/morozov/Projects/phpbrew/vendor/corneltek/pearx/src/PEARX/PackageXml/Parser.php(96): PEARX\Package->addRequiredDependency('arch', Array)
#2 /home/morozov/Projects/phpbrew/src/PhpBrew/Extension/ExtensionFactory.php(310): PEARX\PackageXml\Parser->parse('/home/morozov/....')
#3 /home/morozov/Projects/phpbrew/src/PhpBrew/Extension/ExtensionFactory.php(48): PhpBrew\Extension\ExtensionFactory::createPeclExtension('sqlsrv', '/home/morozov/....')
#4 /home/morozov/Projects/phpbrew/src/PhpBrew/Extension/ExtensionFactory.php(95): PhpBrew\Extension\ExtensionFactory::createFromDirectory('sqlsrv', '/home/morozov/....')
#5 /home/morozov/Projects/phpbrew/src/PhpBrew/Command/ExtensionCommand/InstallCommand.php(153): PhpBrew\Extension\ExtensionFa in /home/morozov/Projects/phpbrew/vendor/corneltek/pearx/src/PEARX/Package.php on line 278

Fatal error: Uncaught Exception: invalid pear dependency type. in /home/morozov/Projects/phpbrew/vendor/corneltek/pearx/src/PEARX/Package.php on line 278

Exception: invalid pear dependency type. in /home/morozov/Projects/phpbrew/vendor/corneltek/pearx/src/PEARX/Package.php on line 278

Call Stack:
    0.0045     397848   1. {main}() /home/morozov/Projects/phpbrew/bin/phpbrew:0
    0.0592     582712   2. CLIFramework\Application->run(???) /home/morozov/Projects/phpbrew/bin/phpbrew:23
    0.0871    1570344   3. CLIFramework\CommandBase->executeWrapper(???) /home/morozov/Projects/phpbrew/vendor/corneltek/cliframework/src/Application.php:398
    0.0872    1570960   4. call_user_func_array:{/home/morozov/Projects/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php:845}(???, ???) /home/morozov/Projects/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php:845
    0.0872    1571352   5. PhpBrew\Command\ExtensionCommand\InstallCommand->execute(???, ???) /home/morozov/Projects/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php:845
    0.0900    1649016   6. PhpBrew\Extension\ExtensionFactory::lookupRecursive(???, ???, ???) /home/morozov/Projects/phpbrew/src/PhpBrew/Command/ExtensionCommand/InstallCommand.php:153
    0.0901    1649472   7. PhpBrew\Extension\ExtensionFactory::createFromDirectory(???, ???) /home/morozov/Projects/phpbrew/src/PhpBrew/Extension/ExtensionFactory.php:95
    0.0901    1649568   8. PhpBrew\Extension\ExtensionFactory::createPeclExtension(???, ???) /home/morozov/Projects/phpbrew/src/PhpBrew/Extension/ExtensionFactory.php:48
    0.0906    1651792   9. PEARX\PackageXml\Parser->parse(???) /home/morozov/Projects/phpbrew/src/PhpBrew/Extension/ExtensionFactory.php:310
    2.5740    1748496  10. PEARX\Package->addRequiredDependency(???, ???) /home/morozov/Projects/phpbrew/vendor/corneltek/pearx/src/PEARX/PackageXml/Parser.php:96
    2.5740    1748496  11. PEARX\Package->validateDependencyType(???) /home/morozov/Projects/phpbrew/vendor/corneltek/pearx/src/PEARX/Package.php:310
```
</details>

The "invalid pear dependency type" is caused by the "arch" dependency (please see the contents below).

<details>
  <summary>package.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<package packagerversion="1.9.0" version="2.0" xmlns="http://pear.php.net/dtd/package-2.0" xmlns:tasks="http://pear.php.net/dtd/tasks-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pear.php.net/dtd/tasks-1.0 http://pear.php.net/dtd/tasks-1.0.xsd http://pear.php.net/dtd/package-2.0 http://pear.php.net/dtd/package-2.0.xsd">
 <name>sqlsrv</name>
 <channel>pecl.php.net</channel>
 <summary>Microsoft Drivers for PHP for SQL Server (SQLSRV)</summary>
 <description>The Microsoft Drivers for PHP for SQL Server are PHP extensions that allow for the reading and writing of SQL Server data from within PHP scripts. The SQLSRV extension provides a procedural interface while the PDO_SQLSRV extension implements PDO for accessing data in all editions of SQL Server 2005 and later (including Azure SQL DB). These drivers rely on the Microsoft ODBC Driver for SQL Server to handle the low-level communication with SQL Server.
*This package contains only the SQLSRV driver.*
 </description>
 <lead>
  <name>Meet Bhagdev</name>
  <user>meetbhagdev</user>
  <email>meetb@microsoft.com</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>Jay Kint</name>
  <user>jkint</user>
  <email>jaykint@microsoft.com</email>
  <active>no</active>
 </lead>
 <lead>
  <name>Marie Barwin</name>
  <user>mbar</user>
  <email>v-mabarw@microsoft.com</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>Hadis Kakanejadi Fard</name>
  <user>hadisfard</user>
  <email>v-hakaka@microsoft.com</email>
  <active>yes</active>
 </lead>
 <date>2017-04-10</date>
 <time>12:55:13</time>
 <version>
  <release>4.1.8preview</release>
  <api>4.1.8</api>
 </version>
 <stability>
  <release>devel</release>
  <api>devel</api>
 </stability>
 <license uri="https://opensource.org/licenses/mit">The MIT License (MIT)</license>
 <notes>
[Added]
- Connection Resiliency now supported in Windows
- Connection pooling now works in MAC
[Fixed]
- Added a workaround for a bug in unixODBC 2.3.4 when connection pooling is enabled
- Fixed the issue in MAC such that the order of which drivers are loaded first no longer matters
- Fixed sqlsrv_num_rows() when the client buffered result is null (issue #330)
- Fixed compilation const char conversion warnings (issue #332)
[Known Issues]
- User defined data types and SQL_VARIANT
 </notes>
 <contents>
  <dir name="/">
   <file md5sum="bd3cd417817aa6be5c77e34529baf929" name="config.m4" role="src" />
   <file md5sum="63ce8379b1388ed3c36ec6f2ecf34f5e" name="config.w32" role="src" />
   <file md5sum="82bcdb254ce51f10913c503bac026b01" name="conn.cpp" role="src" />
   <file md5sum="9498b9dc17a004110404beba42d88850" name="CREDITS" role="doc" />
   <file md5sum="1cb5b7206b558494c116b73119ee6070" name="init.cpp" role="src" />
   <file md5sum="061c9665b46b4db81317457288e2ef9c" name="LICENSE" role="doc" />
   <file md5sum="3771067ae964020a5e27f16c9239327f" name="php_sqlsrv.h" role="src" />
   <file md5sum="e7ece79585f344fdd2e1a831594a2973" name="shared/core_conn.cpp" role="src" />
   <file md5sum="303ca6b1a1f56020a28db748ed733621" name="shared/core_init.cpp" role="src" />
   <file md5sum="b3657ab0f69a50294a9edd913660c885" name="shared/core_results.cpp" role="src" />
   <file md5sum="f4a46ed8f26603e7b25826803a8bc943" name="shared/core_sqlsrv.h" role="src" />
   <file md5sum="89470af7ef0d1b3f578396c46bb6bc82" name="shared/core_stmt.cpp" role="src" />
   <file md5sum="7276cd2d04874b7709650da4d36fac5e" name="shared/core_stream.cpp" role="src" />
   <file md5sum="a347b23abcd4701b5dacf977bb89e510" name="shared/core_util.cpp" role="src" />
   <file md5sum="39e3eaa1e82102bd13648405c9325e0b" name="shared/FormattedPrint.cpp" role="src" />
   <file md5sum="c4a83833d2a41280eec236fd66d9a8a0" name="shared/FormattedPrint.h" role="src" />
   <file md5sum="ca28c3be63d4a592ed07f52d46590f4c" name="shared/globalization.h" role="src" />
   <file md5sum="cc65c9654de01e66e691675b652c1259" name="shared/interlockedatomic_gcc.h" role="src" />
   <file md5sum="8f7ac979b361b08483df804e9ac2db04" name="shared/interlockedatomic.h" role="src" />
   <file md5sum="3f8857e6702e74b4d706feb6edb3ac67" name="shared/interlockedslist.h" role="src" />
   <file md5sum="94b8145e7a9d532376b1ea545b266cdc" name="shared/localization.hpp" role="src" />
   <file md5sum="8e8064b73f3abf59ed9d521ed365bda4" name="shared/localizationimpl.cpp" role="src" />
   <file md5sum="b1050fe718db2305b89f6d186dcd5407" name="shared/msodbcsql.h" role="src" />
   <file md5sum="b71f1a8f6e24eb69efae0a80bf4302e6" name="shared/sal_def.h" role="src" />
   <file md5sum="f967cbebf4713e209c5ced726ec19352" name="shared/StringFunctions.cpp" role="src" />
   <file md5sum="f3f7df2a0bee824bdb823aa64387b90d" name="shared/StringFunctions.h" role="src" />
   <file md5sum="bff0e88c65ca97f744bbd172f5d232d7" name="shared/typedefs_for_linux.h" role="src" />
   <file md5sum="c3333f1c85cd2de20cee4168ea7e0b7d" name="shared/version.h" role="src" />
   <file md5sum="8968ea46df6b21e3caa20ed1cf6c8139" name="shared/xplat.h" role="src" />
   <file md5sum="9df1c78dd7dcdc84273ca25753edec44" name="shared/xplat_intsafe.h" role="src" />
   <file md5sum="6fc764d7d61a7f4894562af02ecc151e" name="shared/xplat_winerror.h" role="src" />
   <file md5sum="83c6e11f145558a0f89996ef9d34118c" name="shared/xplat_winnls.h" role="src" />
   <file md5sum="5a93552b1fcac5ce25a2dbe894454a0d" name="stmt.cpp" role="src" />
   <file md5sum="b04298b0b42556458babb26717ed2ad0" name="template.rc" role="src" />
   <file md5sum="f9576a751a652ab2c65318190749dec4" name="util.cpp" role="src" />
  </dir>
 </contents>
 <dependencies>
  <required>
   <php>
    <min>7.0.0</min>
   </php>
   <pearinstaller>
    <min>1.4.0b1</min>
   </pearinstaller>
   <arch>
    <pattern>linux-*-i?86-*</pattern>
    <conflicts/>
   </arch>   
  </required>
 </dependencies>
 <providesextension>sqlsrv</providesextension>
 <extsrcrelease />
</package>
```
</details>

The installation [will also fail](https://github.com/phpbrew/PEARX/blob/6be60c1a328ca17ec57c011b51cfbb40d9857ff0/src/PEARX/Package.php#L274-L277) if the package depends on the [OS name](https://pear.php.net/manual/en/guide.developers.package2.dependencies.php#guide.developers.package2.dependencies.os).

**Comment by morozov** [comment]
Closing as a duplicate of #6.
